### ISSUE TITLE
Update documentation with font hinting status

### ISSUE THREAD

**Issue by junghandy** [choffmeister/roboto-fontface-bower#15]
In the Material Design specification there is a note indicating that [hinted fonts](http://en.wikipedia.org/wiki/Font_hinting) should be used on Chrome OS, Windows, and Linux. Since hinting can affect the way fonts are rendered in the browser, this prompted me to look at this package to verify that it did have hinting. To verify this I ran a few of the .woff files through [fonttools](https://github.com/behdad/fonttools) and did see that at least a handful of the files did including hinting.

It might be nice to include a note in this package's documentation that the included fonts do include hinting.

**Comment by choffmeister** [comment]
Can you give a list of which files have hinting and which not?

**Comment by junghandy** [comment]
I verified that at least all the WOFF fonts do include hinting. I did not check the other formats.

**Comment by choffmeister** [comment]
OK. I will add a note on that to the README. For the other formats I will check when I get the time for it.
