### ISSUE TITLE
Bad EOT files

### ISSUE THREAD

**Issue by MikeVaz** [choffmeister/roboto-fontface-bower#16]
This repo has issues in .EOT files:
http://stackoverflow.com/questions/9627899/why-is-ie8-not-loading-my-eot-files

**Comment by choffmeister** [comment]
I do not have IE8 at hand to check and since cannot do much. Can you provide working .eot files?

**Comment by MikeVaz** [comment]
Hey. I am still researching that issue. So I haven't tested my solution yet. The fix would be just to use different tool to generate eot file

**Comment by MikeVaz** [comment]
For now I am using this one http://www.fontsquirrel.com/tools/webfont-generator
