### ISSUE TITLE
How does this project keep up to date with Google?

### ISSUE THREAD

**Issue by jiyinyiyong** [choffmeister/roboto-fontface-bower#17]
I noticed Google's roboto repository updates constantly. How do this repo then? Are the fonts files identical with Google's?
https://github.com/google/roboto/commits/master

Thanks.

**Comment by choffmeister** [comment]
No this project is not automatically updated from this repository. The readme of the google/roboto repo says:

> A subset of an earlier version of Roboto is available from Google Fonts, and can be used as a web font."

So, even if the main repository updates regulary, the webfont part, which is what relevant for this package, has been last updated January 2015. This version has been integrated into this repo with #9.

**Comment by jiyinyiyong** [comment]
I didn't look into fonts in `google/roboto`, not sure what was updated. Is there any plan this repo will update to Google's current fonts?

Relate event http://google-opensource.blogspot.sg/2015/05/roboto-googles-signature-font-is-now.html

**Comment by choffmeister** [comment]
No, there is no plan at the moment to keep on track with the general Roboto font. If you can supply a recipe on how to deduce the needed files from `google/roboto` feel free to create a PR with a script that updates the files. I would be highly interested in that.

**Comment by jiyinyiyong** [comment]
@roozbehp ping... what's the updates in Roboto since January please?

**Comment by roozbehp** [comment]
Too many to count, is the short answer. The git log is your best guide.

**Comment by jiyinyiyong** [comment]
Pages of commits >_< 
Do you use this tool in Google? I saw it on you video and it's quite amazing: https://youtu.be/6WxACOHm0_g?t=56

**Comment by choffmeister** [comment]
@jiyinyiyong Are there any more questions 'bout this, or can this be closed?
