### ISSUE TITLE
One Css file per font

### ISSUE THREAD

**Issue by shprink** [choffmeister/roboto-fontface-bower#19]
Hi,

thanks for this lib. I have a suggestion. If you use tools like Webpack or Browserify you may want to only get one type of font and not all of them.

With webpack if you ```require('roboto-fontface')``` you will automatically get all font files (kinda big).

I suggest you separate every type of font in different css files then we will be able to only require what we need like this:  ```require('roboto-fontface/css/Roboto-ThinItalic.css')```

**Comment by choffmeister** [comment]
That is true. But I would still like to keep the all-in-one files. Can you create a PR that adds the indiviual CSS files?

**Comment by shprink** [comment]
Do not really have time for that sorry, just keep it in mind ;)

**Comment by lijunle** [comment]
+1 here. :)

**Comment by mspanc** [comment]
I've created PR.

**Comment by mspanc** [comment]
Now it is one file per weight, that includes both straight and italic, but if you think they should be separate, too, let me know.

**Comment by choffmeister** [comment]
Thx @mspanc for implementing this! Have released a new version 0.4.4 to bower and npm.

**Comment by choffmeister** [comment]
And 0.4.5, because I forgot to update bower.json in 0.4.4 :)
