### ISSUE TITLE
[Feature-Request] Roboto Condensed

### ISSUE THREAD

**Issue by marcel-burkhard** [choffmeister/roboto-fontface-bower#21]
I'd like to see the 'Roboto Condensed' typefaces included.

You can get them on fontsquirrel: http://www.fontsquirrel.com/fonts/roboto

**Comment by choffmeister** [comment]
Sry for the long time that has passed by.

Would like to include it, if you create a PR for this.

**Comment by choffmeister** [comment]
Might be solved with https://github.com/choffmeister/roboto-fontface-bower/pull/28

**Comment by marcel-burkhard** [comment]
Sorry, I am no longer working on projects in which this is relevant to me.
Therefore I'm not going to validate wether that Pull Request would solve my Feature Request.

**Comment by choffmeister** [comment]
No problem. So can you close this issue then, if it is not relevant for you anymore?

**Comment by marcel-burkhard** [comment]
yeah sure
