### ISSUE TITLE
Case-sensitivity in URLs

### ISSUE THREAD

**Issue by thatguystone** [choffmeister/roboto-fontface-bower#30]
It looks like the URLs created from sass + less are being created as something like, `.../Roboto/Roboto-Light.woff2`, instead of `.../roboto/Roboto-Light.woff2`. On a case-sensitive filesystem (Linux, in my case), this means that the files can't be found.

Any thoughts on the best way to address this? A few options I thought of:

1. Rename `roboto` to `Roboto`, but I fear that would break other things.
1. Use sass's `to-lower-case` function, but less lacks a similar function.
1. Add an extra, properly-cased arg to the mixin, but that's just a lot of repeated crap.

**Comment by sontek** [comment]
I just ran into this issue as well.

```
Module not found: Error: Cannot resolve 'file' or 'directory' ../../../fonts/Roboto/Roboto-BlackItalic.ttf in /Users/sontek/src/app/static/sass
```

Because its looking for `Roboto` instead of `roboto`

**Comment by skorenuk** [comment]
I used webpack and sass loader and I resolved issue like this:
$roboto-font-path: '~roboto-fontface/fonts' !default;
then:
@import "~roboto-fontface/css/roboto/sass/roboto-fontface.scss";

But then I got another errors
Cannot resolve module 'roboto-fontface/fonts/Roboto/Roboto/Roboto-Black.eot'
twice ...Roboto/Roboto/...

Error coz of this line
https://github.com/choffmeister/roboto-fontface-bower/blob/develop/css/mixins.scss#L23

**Comment by paralin** [comment]
Fixed by #31

**Comment by choffmeister** [comment]
Thanks @Badou90 for fixing this bug.

**Comment by paralin** [comment]
@choffmeister Thank you for the quick turnaround, everything seems good now.
