### ISSUE TITLE
Create separate folders for LESS, SCSS and CSS

### ISSUE THREAD

**Issue by pedzed** [choffmeister/roboto-fontface-bower#32]
If I import like this:

``` scss
@import '../../../public/vendor/bower/roboto-fontface/css/roboto-fontface';
```

Then my preprocessor complains about not knowing whether to load `.css` or `.scss`.

If I change it to this:

``` scss
@import '../../../public/vendor/bower/roboto-fontface/css/roboto-fontface.scss';
```

Then my SCSS linter complains.

Please, move the files to separate folders, like everybody else does (e.g. [FontAwesome](https://github.com/FortAwesome/Font-Awesome)).

**Comment by choffmeister** [comment]
There are different folders for css/sass/less. As stated in the README.md, you have to use

```sass
@import '../../../public/vendor/bower/roboto-fontface/css/roboto-condensed/sass/roboto-condensed-fontface.scss';
```

Although the nesting of less/scss in the css folder might not be ideal, there you are right.

**Comment by choffmeister** [comment]
@pedzed Since you did not reply and I think your whish to have different folders for css/less/sass is already in place, I will close this. Feel free to reopen if you disagree.
