### ISSUE TITLE
use only WOFF and WOFF2

### ISSUE THREAD

**Issue by DanielRuf** [choffmeister/roboto-fontface-bower#43]
We should use WOFF and WOFF 2 and remove the other old formats to improve the loading times.

http://caniuse.com/#feat=woff
http://caniuse.com/#feat=woff2

**Comment by Samuell1** [comment]
Yes! SVG files have  together around 8MB.

**Comment by choffmeister** [comment]
Are the loading times influenced by this anyway? I am pretty sure that the browser only fetches one set of files in his most preferred supported format. Or does the browser really load all files?

**Comment by choffmeister** [comment]
Anyhow, if you provide a PR I would be happy to merge it.

**Comment by Samuell1** [comment]
@choffmeister i using this package in electron app, when i compile all font types are compiled thats why sometimes size matters

**Comment by choffmeister** [comment]
@Samuell1 That is a true point. So: If you provide a PR then I will merge it.

**Comment by DanielRuf** [comment]
> @Samuell1 That is a true point. So: If you provide a PR then I will merge it.

Do you mean me?

**Comment by Samuell1** [comment]
@choffmeister maybe 2 packages will be better if somebody needs svg etc... `normal` and `optimized`

**Comment by choffmeister** [comment]
@DanielRuf No, I meant @Samuell1 with his electron app example :D

When all major browsers support WOFF(2) then there should be no real usecase anymore for the SVG files. Or do you have a usecase in mind?

**Comment by DanielRuf** [comment]
http://caniuse.com/#feat=woff
http://caniuse.com/#feat=woff2

woff is used as fallback if woff2 is not supported (load woff2 first in the font-face declaration).

**Comment by DanielRuf** [comment]
Personally I see no modern usecase for svg, maybe just in specific environments and GUI frameworks like Swing, SWT, AWT, ... for Java and so on.

**Comment by DanielRuf** [comment]
Bump.

**Comment by choffmeister** [comment]
@DanielRuf I would be open to merge a PR. But one more question: Wouldn't resorting the loading order to `woff2 > woff > ttf > ...` also solve the loading time issue? The browser does not load additional formats, if it already has a working one, right?

**Comment by DanielRuf** [comment]
Generally, the order is always woff2, woff as the first one that matches will be used. So yes, this would at least improve it. But still, ttf is not needed in web and has less features than the others and is also bigger ;-)

**Comment by choffmeister** [comment]
@DanielRuf True. So if you provide a PR that drops everything but woff2,woff then I will merge it and release it as new minor version

**Comment by DanielRuf** [comment]
See https://github.com/choffmeister/roboto-fontface-bower/pull/57
