### ISSUE TITLE
There seems to be a discrepancy of path upper/lower case now

### ISSUE THREAD

**Issue by richtera** [choffmeister/roboto-fontface-bower#49]
I just pulled latest and it broke my font paths. Turns out the sass rules now use to_lowercase for the variant rule which is fine in terms of the css folder, but the fonts folder uses upper case for the variants. So I now have some fake mapping in my webpack, but it seems wrong. Either it should use upper case for the variant or change the folders in the fonts folder to lower case.

**Comment by choffmeister** [comment]
Fixed and released as `@0.8.0`
