### ISSUE TITLE
Roboto-Thin not found in 0.8.0

### ISSUE THREAD

**Issue by esseswann** [choffmeister/roboto-fontface-bower#51]
I just updated the version and this error poped up:
`Module not found: Can't resolve '../../fonts/roboto/Roboto-Thin.eot' in '...node_modules\roboto-fontface\css\roboto'`

**Comment by HitomiTenshi** [comment]
Same issue here with pretty much every font.

It happens because version `0.8.0` references the wrong path.

- url in `0.7.1`: url('../../fonts/Roboto/Roboto-Thin.eot?#iefix')
- url in `0.8.0`: url('../../fonts/roboto/Roboto-Thin.eot?#iefix')

The folder is called `Roboto` with an upper case first letter. In `0.8.0` it searches for the folder with a lower case first letter.

**Comment by BrandonSmith** [comment]
Also seeing similar issue with my webpack build:

`ERROR in ./node_modules/css-loader!./node_modules/postcss-loader/lib?{}!./app/web/css/roboto-fontface.css
Module not found: Error: Can't resolve 'roboto-fontface/fonts/Roboto/Roboto-Thin.woff2' in '/home/jenkins/workspace/Anywhere Linux Channel/app/web/css'
 @ ./node_modules/css-loader!./node_modules/postcss-loader/lib?{}!./app/web/css/roboto-fontface.css 6:144-201 6:397-454
 @ ./app/web/css/roboto-fontface.css
 @ ./app/web/js/onboard.js`

Changing the path to a lowercase `roboto` folder name fixed it.

**Comment by HitomiTenshi** [comment]
This is a bug for my build, because I copy the fonts directly from `node_modules/roboto-fontface` during my release scripts. I don't keep my own copy in order to keep up with updates of this package. I'll stick to `0.7.1` for now and hope this gets fixed someday.

**Comment by choffmeister** [comment]
Looking at what is checked into the source, the folder is now correctly in lower cases. Please try to remove your `node_modules/roboto-fontface/` and then run `npm install roboto-fontface@0.8.0` again. I guess your machines just does not rename the already existing folders.

**Comment by HitomiTenshi** [comment]
I already tried deleting the whole `node_modules` folder and running `npm install` again. It previously didn't make the folder lower case.

I just tried it again and it seems to have installed it correctly now... weird.

Issue can be closed then I guess. Maybe the `npm-cache` folder still had the upper case folder name or something. It's fixed now.

**Comment by choffmeister** [comment]
Great.
