### ISSUE TITLE
Font differ with font from google

### ISSUE THREAD

**Issue by AntonovAv** [choffmeister/roboto-fontface-bower#52]
Hello, 
I add this package into my project instead fonts from google 
But height of letters little differ. (see red arrows on screenshot).   
Left - `roboto-fontface`
include into project with:   
```
@import url("../../node_modules/roboto-fontface/css/roboto/roboto-fontface.css");
```
Right - fonts from google
include into project with:   
```
@import url(http://fonts.googleapis.com/css?family=Roboto:100,100italic,200,300,300ita‌​lic,400,400italic,500,500italic,700,700italic,900italic,900);
```
![image](https://user-images.githubusercontent.com/11208532/28372829-6d9df046-6ca9-11e7-8363-01ae00269517.png)

any ideas?

**Comment by DanielRuf** [comment]
Probably not the last release from Google.
