### ISSUE TITLE
Hinting differs from that of Google Fonts API version

### ISSUE THREAD

**Issue by RoyCurtis** [choffmeister/roboto-fontface-bower#9]
The bower package of Roboto font-face appears to have different (subjectively, inferior) hinting than the version hosted by Google on their Fonts API.

Using `"roboto-fontface": "~0.2.5"` on Bower and `http://fonts.googleapis.com/css?family=RobotoDraft:regular,bold,italic,thin,light,bolditalic,black,medium&lang=en` for API (I assume "RobotoDraft" is an internal name)

## Comparison
* Chrome 39
  * [roboto-fontface](http://i.imgur.com/vw4xKh7.png)
  * [Fonts API](http://i.imgur.com/uSIzmxL.png)
* Firefox 33.02
  * [roboto-fontface](http://i.imgur.com/PWp9x5D.png)
  * [Fonts API](http://i.imgur.com/zTPpjt3.png)

**Comment by davidpolberger** [comment]
Roboto was updated on Google Fonts on January 14, 2015. Perhaps it is time to reopen this issue?

https://www.google.com/fonts/specimen/Roboto

**Comment by choffmeister** [comment]
Will have a look at it soon. Or if anyone likes to supply an PR, go for it :)

**Comment by choffmeister** [comment]
This issue has been solved by #12.

**Comment by anettan** [comment]
Unfortunately, it does not seem to clarify whether these changes will become "Roboto" or be kept separate as "RobotoDraft",?

**Comment by choffmeister** [comment]
When looking at the PR #12 you can see, that all font files have been replaced. The old version has been discarded, and the current version from https://www.google.com/fonts/specimen/Roboto January 14 2015 has beed added under the name "Roboto".
